In [28]:
import time
print(time.ctime())

Wed Feb 15 09:33:35 2023


In [4]:
import numpy as np

In [3]:
x = 1
y = x+1
x=2
y

2

In [6]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [8]:
y = np.array([[1, 4, 3], [3, 2, 7]])
y

array([[1, 4, 3],
       [3, 2, 7]])

In [11]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[2,3,4], [1,2,3], [6,7,8]]])
z

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[2, 3, 4],
        [1, 2, 3],
        [6, 7, 8]]])

In [12]:
def my_adder(a, b, c):
  """
  function to sum the 3 numbers
  Input: 3 numbers a, b, c
  Output: the sum of a, b, and c
  author:
  date:
  """
  # this is the summation
  out = a + b + c

  return out

In [13]:
my_adder(1,2,3)

6

In [16]:
help(my_adder)

Help on function my_adder in module __main__:

my_adder(a, b, c)
    function to sum the 3 numbers
    Input: 3 numbers a, b, c
    Output: the sum of a, b, and c
    author:
    date:



In [17]:
def my_thermo_stat(temp, desired_temp):
  if temp < desired_temp - 5:
    status = "Heat"
  elif temp > desired_temp + 5:
    status = "AC"
  else:
    status = "off"
  return status

In [18]:
status = my_thermo_stat(65,75)
print(status)

Heat


In [19]:
status = my_thermo_stat(75,65)
print(status)

AC


In [20]:
status = my_thermo_stat(65,63)
print(status)

off


In [27]:
x = 3
if 1<x<2:
  y = 2
if 2<x<4:
  y = 4
else:
  y = 0
print(y)

4
